"""capture_telemetry.py 보고서용 필드 사전.

RAW: MAVSDK 4.x Telemetry 스트림 → (스트림 설명, {필드: 의미})
     필드가 없는 스트림(bool·enum 단일값)은 빈 dict.
PROCESSED: UAV Agent 응답 필드 → 의미
"""

RAW = {
    "actuator_control_target": ("제어기가 액추에이터에 내리는 목표값 (정규화된 제어 입력)", {}),
    "actuator_output_status": ("실제 모터·서보 출력값 (PWM 등)", {}),
    "altitude": ("여러 기준의 고도", {
        "altitude_amsl_m": "해발고도 (m)",
        "altitude_local_m": "로컬 원점(EKF 원점) 기준 고도 (m)",
        "altitude_monotonic_m": "추정기 리셋 시에도 튀지 않도록 보정한 연속 고도 (m)",
        "altitude_relative_m": "홈(이륙 지점) 기준 상대고도 (m)",
        "altitude_terrain_m": "지면 기준 고도 (m). 거리센서가 없으면 NaN",
        "bottom_clearance_m": "기체 아래 지면·장애물까지 거리 (m). 거리센서가 없으면 NaN",
        "timestamp_us": "PX4 부팅 후 경과 시간 (µs)",
    }),
    "armed": ("시동 여부 (true = 모터 회전 가능)", {}),
    "attitude_angular_velocity_body": ("기체 좌표계 각속도", {
        "roll_rad_s": "롤 축 회전 속도 (rad/s)",
        "pitch_rad_s": "피치 축 회전 속도 (rad/s)",
        "yaw_rad_s": "요 축 회전 속도 (rad/s)",
    }),
    "attitude_euler": ("자세 (오일러각)", {
        "roll_deg": "좌우 기울기 (°, 오른쪽 날개 아래가 +)",
        "pitch_deg": "앞뒤 기울기 (°, 기수 위가 +)",
        "yaw_deg": "기수 방향 (°, 북 기준 시계방향)",
        "timestamp_us": "PX4 부팅 후 경과 시간 (µs)",
    }),
    "attitude_quaternion": ("자세 (쿼터니언). attitude_euler 와 같은 정보의 다른 표현", {
        "w": "쿼터니언 스칼라 성분", "x": "쿼터니언 x 성분", "y": "쿼터니언 y 성분", "z": "쿼터니언 z 성분",
        "timestamp_us": "PX4 부팅 후 경과 시간 (µs)",
    }),
    "battery": ("배터리 상태", {
        "battery_function": "배터리 용도 (ALL = 전체 계통 전원)",
        "capacity_consumed_ah": "소모한 용량 (Ah). 용량 설정(BAT1_CAPACITY)이 없으면 0",
        "current_battery_a": "현재 전류 (A). 전류 측정이 없으면 NaN",
        "id": "배터리 번호",
        "remaining_percent": "잔량 (%, 0~100). PX4 내부 0~1 값을 MAVSDK 가 ×100",
        "temperature_degc": "배터리 온도 (°C). 측정 없으면 NaN",
        "time_remaining_s": "예상 잔여 시간 (s). 추정 불가 시 NaN",
        "voltage_v": "전압 (V)",
    }),
    "distance_sensor": ("하방 거리센서 (라이다·초음파) 측정값. 기체에 센서 없음", {}),
    "fixedwing_metrics": ("비행 계기값 (MAVLink VFR_HUD). 이름과 달리 멀티콥터도 발행", {
        "absolute_altitude_m": "해발고도 (m)",
        "airspeed_m_s": "대기속도 (m/s). 대기속도 센서가 없으면 NaN",
        "climb_rate_m_s": "상승률 (m/s, 위가 +)",
        "groundspeed_m_s": "대지속도 (m/s)",
        "heading_deg": "기수 방향 (°, 0~360)",
        "throttle_percentage": "스로틀 출력 (MAVSDK 명칭은 %, 값 척도 미확인)",
    }),
    "flight_mode": ("PX4 비행 모드 (HOLD, TAKEOFF, MISSION, RETURN_TO_LAUNCH, LAND 등)", {}),
    "gps_info": ("GPS 수신 상태 요약", {
        "fix_type": "측위 종류 (NO_FIX, FIX_2D, FIX_3D, RTK_FLOAT, RTK_FIXED 등)",
        "num_satellites": "사용 중인 위성 수",
    }),
    "ground_truth": ("시뮬레이터 참값 위치 (실기체에는 없음)", {}),
    "heading": ("기수 방향", {"heading_deg": "기수 방향 (°, 북 기준 시계방향)"}),
    "health": ("비행 전 점검 항목", {
        "is_accelerometer_calibration_ok": "가속도계 보정 완료",
        "is_armable": "지금 시동을 걸 수 있는 상태",
        "is_global_position_ok": "GPS 기반 전역 위치 추정 가능",
        "is_gyrometer_calibration_ok": "자이로 보정 완료",
        "is_home_position_ok": "홈 위치 설정됨",
        "is_local_position_ok": "로컬 위치 추정 가능",
        "is_magnetometer_calibration_ok": "지자기계 보정 완료",
    }),
    "health_all_ok": ("health 전 항목이 모두 true 인지", {}),
    "home": ("홈(이륙·복귀) 위치", {
        "latitude_deg": "위도 (°)", "longitude_deg": "경도 (°)",
        "absolute_altitude_m": "해발고도 (m)",
        "relative_altitude_m": "홈 기준 상대고도 (항상 0)",
        "local_north_m": "로컬 원점 기준 북쪽 거리 (m)",
        "local_east_m": "로컬 원점 기준 동쪽 거리 (m)",
        "local_down_m": "로컬 원점 기준 아래쪽 거리 (m, 위가 −)",
        "approach_north_m": "착륙 접근 방향 벡터 북 성분 (m)",
        "approach_east_m": "착륙 접근 방향 벡터 동 성분 (m)",
        "approach_down_m": "착륙 접근 방향 벡터 하 성분 (m)",
        "q": "홈 위치에서의 기체 방향 (쿼터니언)",
        "timestamp_us": "홈이 설정된 시각 (PX4 부팅 후 µs)",
    }),
    "imu": ("IMU 측정값 (가속도·각속도·자기장·온도)", {}),
    "in_air": ("비행 중 여부 (true = 공중)", {}),
    "landed_state": ("착륙 상태 (ON_GROUND, TAKING_OFF, IN_AIR, LANDING, UNKNOWN)", {}),
    "odometry": ("위치·속도·자세 통합 추정값", {}),
    "position": ("전역 위치 (EKF 추정)", {
        "latitude_deg": "위도 (°)", "longitude_deg": "경도 (°)",
        "absolute_altitude_m": "해발고도 (m)",
        "relative_altitude_m": "홈(이륙 지점) 기준 상대고도 (m). 지면 기준 AGL 아님",
    }),
    "position_velocity_ned": ("로컬 원점 기준 위치·속도 (NED: 북·동·아래)", {
        "position.north_m": "북쪽 거리 (m)", "position.east_m": "동쪽 거리 (m)",
        "position.down_m": "아래쪽 거리 (m, 위가 −)",
        "velocity.north_m_s": "북쪽 속도 (m/s)", "velocity.east_m_s": "동쪽 속도 (m/s)",
        "velocity.down_m_s": "하강 속도 (m/s, 상승이 −)",
    }),
    "raw_gps": ("GPS 수신기 원시값", {
        "latitude_deg": "위도 (°)", "longitude_deg": "경도 (°)",
        "absolute_altitude_m": "해발고도 (m)",
        "altitude_ellipsoid_m": "WGS84 타원체 기준 고도 (m)",
        "cog_deg": "진행 방향 (Course Over Ground, °). 정지 중에는 의미 없음",
        "hdop": "수평 정밀도 저하율 (작을수록 좋음, 1 이하 양호)",
        "vdop": "수직 정밀도 저하율 (작을수록 좋음)",
        "horizontal_uncertainty_m": "수평 위치 오차 추정 (m)",
        "vertical_uncertainty_m": "수직 위치 오차 추정 (m)",
        "velocity_m_s": "대지속도 (m/s)",
        "velocity_uncertainty_m_s": "속도 오차 추정 (m/s)",
        "heading_uncertainty_deg": "방향 오차 추정 (°)",
        "yaw_deg": "GPS 기반 방향 (°). 듀얼 안테나가 없으면 0",
        "timestamp_us": "PX4 부팅 후 경과 시간 (µs)",
    }),
    "raw_imu": ("IMU 원시 측정값", {}),
    "rc_status": ("RC 조종기 연결 상태", {
        "is_available": "현재 조종기 연결됨",
        "signal_strength_percent": "신호 세기 (%). 연결 없으면 NaN",
        "was_available_once": "한 번이라도 연결된 적 있음",
    }),
    "scaled_imu": ("단위 변환된 IMU 측정값", {}),
    "scaled_pressure": ("기압계", {
        "absolute_pressure_hpa": "대기압 (hPa). 기압고도 계산에 사용",
        "differential_pressure_hpa": "차압 (hPa). 대기속도 센서용, 멀티콥터는 0",
        "differential_pressure_temperature_deg": "차압 센서 온도 (°C)",
        "temperature_deg": "기압계 온도 (°C)",
        "timestamp_us": "PX4 부팅 후 경과 시간 (µs)",
    }),
    "status_text": ("PX4 경고·안내 메시지. 발생할 때만 전송", {}),
    "unix_epoch_time": ("PX4 시스템 시각 (Unix epoch µs)", {}),
    "velocity_ned": ("속도 (NED)", {
        "north_m_s": "북쪽 속도 (m/s)", "east_m_s": "동쪽 속도 (m/s)",
        "down_m_s": "하강 속도 (m/s, 상승이 −)",
    }),
    "vtol_state": ("VTOL 전환 상태. 멀티콥터(x500)는 UNDEFINED", {}),
    "wind": ("풍속·풍향 추정값", {}),
}

INFO = {
    "version": "PX4 펌웨어·OS 버전 (flight_sw_* = PX4, os_sw_* = 호스트 OS)",
    "identification": "기체 고유 ID (SITL 은 0)",
    "product": "제조사·제품 정보 (SITL 은 undefined)",
    "speed_factor": "시뮬레이션 속도 배율 (1.0 = 실시간)",
    "gps_global_origin": "EKF 로컬 원점의 위경도·고도. 로컬 NED 좌표의 기준점",
}

PROCESSED_STATE = {
    "uav_id": "이 서버가 담당하는 UAV ID (팀 표기 resource_id)",
    "timestamp": "UAV 서버가 응답을 만든 시각 (ISO8601 UTC). PX4 측정 시각 아님",
    "position.lat": "위도 (°, WGS84)",
    "position.lon": "경도 (°, WGS84)",
    "position.alt_m_amsl": "해발고도 (m)",
    "position.alt_m_agl": "이륙 지점 기준 상대고도 (m). 지면 기준 아님",
    "battery.percent": "배터리 잔량 (%, 0~100)",
    "battery.voltage": "배터리 전압 (V)",
    "velocity_ms": "수평 속도 (m/s)",
    "flight_mode": "PX4 비행 모드 이름",
    "armed": "시동 여부",
    "health.gps_ok": "GPS 기반 위치 추정 가능",
    "health.sensors_ok": "자이로·가속도계·지자기계 보정 모두 완료",
    "health.failsafe": "PX4 failsafe 작동 중 (real 에서는 항상 false, 고정값)",
    "wind_ms": "풍속 (m/s). real 에서는 항상 null (PX4 미발행)",
    "link_quality": "통신 상태 (real 에서는 항상 \"OK\", 고정값)",
    "current_task_id": "수행 중인 Task (현재 항상 null, 미구현)",
}

PROCESSED_EVALUATE = {
    "task_id": "요청의 Task ID (그대로 반환)",
    "decision_id": "요청의 판단 ID (그대로 반환)",
    "uav_id": "판단한 UAV",
    "verdict": "ACCEPT(수행 가능) / REJECT(불가) / COUNTER(조건부 가능)",
    "eta_sec": "목표 상공 도착 예상 시간 (s). 상승 시간 포함. REJECT 는 null",
    "reason": "REJECT·COUNTER 사유 코드 (interfaces/schema.py RejectReason)",
    "detail": "사람이 읽는 설명 (일부 REJECT 만)",
    "counter_offer": "COUNTER 일 때 제안 조건",
    "constraints.distance_km": "현재 위치 → 목표 수평 거리 (km)",
    "constraints.battery_now_pct": "현재 배터리 (%)",
    "constraints.battery_after_pct": "왕복 + 관측 후 예상 배터리 (%)",
    "constraints.return_margin_pct": "복귀 후 남는 배터리 (%). 20 미만이면 COUNTER",
    "constraints.wind_ms": "판단에 쓴 풍속 (m/s, 요청값)",
    "constraints.required_climb_m": "목표 비행고도(목표 지면 + 50 m)까지 상승량 (m)",
    "constraints.eta_sec": "ETA (s). REJECT 여도 계산된 경우 여기 남음",
}
